# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_auto_20171206_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationmodel',
            name='gender',
        ),
    ]
